DROP TABLE IF EXISTS simple_role;
CREATE TABLE simple_role
(
    id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(30) NOT NULL
);
DROP TABLE IF EXISTS simple_user;
CREATE TABLE simple_user
(
    id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(30) NOT NULL,
    user_info_id BIGINT
);
DROP TABLE IF EXISTS simple_user_role;
CREATE TABLE simple_user_role
(
    id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL
);
DROP TABLE IF EXISTS user_info;
CREATE TABLE user_info
(
    id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(30),
    last_name VARCHAR(30),
    address VARCHAR(255)
);
